### PR TITLE
WriteAttribute needs to exist on the ViewBase

### PR DESCRIPTION
**Pull request by nmosafi**
Without this, we can't use attributes in our views. Adding the attribute to the test cshtml files shows this, I think the implementation is right but not 100% certain, seems to work though

### CODE REVIEW

**Comment by serialseb** [comment]
Will take your word for it. If it breaks someone they can submit another pull request.

**Comment by nmosafi** [comment]
It can't be worse than what it does now :-)

**Comment by serialseb** [comment]
Don’t blame me, not my code. :)))

## 

Seb

On 23 Dec 2014, at 19:06, Neil Mosafi <notifications@github.com<mailto:notifications@github.com>> wrote:

It can't be worse than what it does now :-)

**Comment by nmosafi** [comment]
I know, I think it broke on the upgrade to Razor v2 or something :)

I think I am actually the only one using this these days

**Comment by serialseb** [comment]
I’m gonna bring it back to OR3 but using a fork of the current codebase and move to a Resource property rather than @model to please resharper. SHould make it more portable too.

On 23 Dec 2014, at 19:10, Neil Mosafi <notifications@github.com<mailto:notifications@github.com>> wrote:

I know, I think it broke on the upgrade to Razor v2 or something :)

I think I am actually the only one using this these days

**Comment by nmosafi** [comment]
Yeah R# does not like @resource

**Pull request merged**
