### PR TITLE
Allow views to be specified as ~/Views/MyView.cshtml in the Configuration

### PR DESCRIPTION
**Pull request by nmosafi**
Allow views to be specified as ~/Views/MyView.cshtml in the Configuration so it can be used with both standalone hosting or Asp.Net hosting with views embedded in the assembly

### CODE REVIEW

**Comment by nmosafi** [comment]
BUMP!

**Comment by serialseb** [comment]
replacing all / with . is fine. That said i'd rather we only remove the ~ if it's at the beginning. It is after all a valid path character. If you can reissue with that i'll merge it now.

**Comment by nmosafi** [comment]
Sure. Will do

**Comment by nmosafi** [comment]
Try now :)

**Comment by holytshirt** [comment]
Wow this has some life, I'll clean up the project and get it nuget'd. Would you like that?

**Comment by serialseb** [comment]
That would be great :)

**Comment by holytshirt** [comment]
@nmosafi I assume you use this project? I have a branch where I've updated all the things https://github.com/openrasta/openrasta-codecs-razor/tree/upgrade_all_the_things . This now uses the latest version of OpenRasta and updated to Razor 2. It has a build now on https://ci.appveyor.com/project/holytshirt/openrasta-codecs-razor which outputs a nuget package too, ready to deploy to Nuget feed. You can test the nuget packed from here https://ci.appveyor.com/project/holytshirt/openrasta-codecs-razor/build/artifacts . @serialseb  This is a large change, but can you give it a sanity check?

**Comment by holytshirt** [comment]
Bump @nmosafi  @serialseb

**Comment by nmosafi** [comment]
Yes I use it. Will take a look this week at these changes, hopefully all
will be good

**Comment by serialseb** [comment]
If you both +1 the changes just pull them in and let's release a package.

Sent from my iPad

On 22 Oct 2014, at 18:39, Toby Henderson <notifications@github.com<mailto:notifications@github.com>> wrote:

@nmosafihttps://github.com/nmosafi I assume you use this project? I have a branch where I've updated all the things https://github.com/openrasta/openrasta-codecs-razor/tree/upgrade_all_the_things . This now uses the latest version of OpenRasta and updated to Razor 2. It has a build now on https://ci.appveyor.com/project/holytshirt/openrasta-codecs-razor which outputs a nuget package too, ready to deploy to Nuget feed. You can test the nuget packed from here ttps://ci.appveyor.com/project/holytshirt/openrasta-codecs-razor/build/artifacts . @serialsebhttps://github.com/serialseb This is a large change, but can you give it a sanity check?

##

**Comment by nmosafi** [comment]
I'm good for taking this in. Will test my apps with all the latest NuGet OpenRasta bits and see if anything goes wrong

**Comment by nmosafi** [comment]
Has this been merged into the NuGet yet, I'm ready to test it all with our apps?

**Comment by holytshirt** [comment]
It's not on the main nuget feed yet, above I have a link to a nuget package for you to test. I can put it on the main feed if that is easier for you?

**Comment by serialseb** [comment]
Just go for it, no harm done, right?

## 

On 10 Nov 2014, at 21:24, Toby Henderson <notifications@github.com<mailto:notifications@github.com>> wrote:

It's not on the main nuget feed yet, above I have a link to a nuget package for you to test. I can put it on the main feed if that is easier for you?

**Comment by nmosafi** [comment]
I agree with Seb

**Comment by holytshirt** [comment]
Done 

Install-Package openrasta-razor

Let me know how you get on

**Comment by holytshirt** [comment]
https://www.nuget.org/packages/openrasta-razor/

Sorry was out this evening and only just got back.

**Comment by nmosafi** [comment]
Cheers. Will check tomorrow!

**Comment by nmosafi** [comment]
I just checked and it's still not working, then I looked at the source and doesn't look like this has been merged in

https://github.com/openrasta/openrasta-codecs-razor/blob/master/src/OpenRasta.Codecs.Razor/EmbeddedViewProvider.cs

**Comment by holytshirt** [comment]
Added it, give it a moment to build and I'll push the new package

**Comment by holytshirt** [comment]
Done, version openrasta-razor 2.5.4 is pushed to nuget, with your change. We are also pushing to symbolsource so debugging should be a nice experience for you :)

**Comment by holytshirt** [comment]
@nmosafi did it work?

**Comment by nmosafi** [comment]
I'm on holiday now. Back on Monday so will test then

**Comment by serialseb** [comment]
So can we close this?

**Comment by nmosafi** [comment]
Oops, haven't tested it yet! Will check tomorrow bro

**Comment by nmosafi** [comment]
Have checked the nuget and found some issues, managed to replicate and reproduce.  Please see the two pull requests which I submitted.

Thanks!

**Comment by serialseb** [comment]
Seems inoffensive. Plus you're the only user. Im pulling it in.

**Pull request merged**
